members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
  path('', views.main, name='main'),
  path('members/', views.members, name='members'),
  path('members/detail/<slug:slug>/', views.details, name='details'),
  path('testing/', views.testing, name='testing'),
]

my_tennis_club/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
]

members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    phone = models.IntegerField(null=True)
    joined_date = models.DateField(null=True)
    slug = models.SlugField(default='', null=False)

    def __str__(self):
        return f"{self.firstname} {self.lastname}"

members/views.py
from django.http import HttpResponse
from django.template import loader
from django.db.models import Q

from .models import Member

def members(request):
  members = Member.objects.all().values()
  template = loader.get_template('all_members.html')
  context = {
    'members': members,
  }
  return HttpResponse(template.render(context, request))

def details(request, slug):
  member = Member.objects.get(slug=slug)
  template = loader.get_template('details.html')
  context = {
    'member': member
  }
  return HttpResponse(template.render(context, request))

def main(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

def testing(request):
  ### -- QuerySet Get -- ###

  members = Member.objects.all().values()

  # Return a specific column
  firstnames = Member.objects.values_list('firstname')
  
  ### ------------------ ###

  ### -- QuerySet Filter (for more: https://www.w3schools.com/django/django_queryset_filter.php) -- ###
  
  # Return particular rows
  emily_data = Member.objects.filter(firstname='Emily').values()
  refsnes_id2 = Member.objects.filter(lastname='Refsnes', id=2).values()
  
  # (1) [extended version]
  tobias_or_emil = Member.objects.filter(firstname='Emil').values() | Member.objects.filter(firstname='Tobias').values()
  # (2) [same with (1), but still common] 
  mesut_or_smith = Member.objects.filter(Q(firstname='Mesut') | Q(firstname='Smith')).values()

  # Field Lookups syntax
  member_whose_firstname_starts_from_l = Member.objects.filter(firstname__startswith='L').values() # <- ... WHERE firstname LIKE 'L%'
  ### --------------------- ###

  ### -- QuerySet Order By -- ###
  members_ordered_by_firstname = Member.objects.all().order_by('firstname').values() # SELECT * FROM members ORDER BY firstname;
  members_descendingly_ordered_by_firstname = Member.objects.all().order_by('-firstname').values() # SELECT * FROM members ORDER BY firstname DESC;

  # Multiple Order Bys
  members_multi_ordered_by = Member.objects.all().order_by('lastname', '-id').values() # SELECT * FROM members ORDER BY lastname ASC, id DESC;
  ### ----------------------- ###

  template = loader.get_template('template.html')
  context = {
    'fruits': ['Apple', 'Banana', 'Manggo'],
    'fav_food': ['Apple', 'Banana', 'Manggo'],
    'pricey_fruits': ['Grape', 'Tomato', 'Pineapple'],
    'firstname': 'Linus',
    'members': members,
    'greeting': 1,
    'eat_fruits': True,
    'day': 'Friday',
    'firstnames': firstnames,
    'emily_data': emily_data,
    'refsnes_id2': refsnes_id2,
    'tobias_or_emil': tobias_or_emil,
    'mesut_or_smith': mesut_or_smith,
  }
  return HttpResponse(template.render(context, request))

members/templates/all_members.html
{% extends 'master.html' %}

{% block title %}
    My Tennis Club - List of all members
{% endblock %}

{% block content %}
    <h3>Members</h3>
    <ul>
        {% for member in members %}
            <li>
                {% comment 'Either of the following works' %}{% endcomment %}
                <!-- <a href="/members/detail/{{ member.id }}">{{member.firstname}} {{member.lastname}}</a> -->
                <a href="{% url 'members:details' member.slug %}">{{member.firstname}} {{member.lastname}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

members/templates/details.html
{% block title %}
    Details about {{ member.firstname }} {{ member.lastname }}
{% endblock %}

{% block content %}
    <h1>{{ member.firstname }} {{ member.lastname }}</h1>

    <p>Phone: {{ member.phone }}</p>
    <p>Member since: {{ member.joined_date }}</p>

    <p>Back to <a href="/members">Member list</a></p>
{% endblock %}

members/templates/footer.html
<div>
    <h3>Footer</h3>
    <p>You have reached the bottom of the page, thanks for viewing!</p>
</div>

members/templates/main.html
{% extends 'master.html' %}

{% block title %}
    My Tennis Club
{% endblock %}

{% block content %}
    <div class="main">
        <h3>My Tennis Club</h3>
        <h4>Members</h4>
        <p>
            Check out all our <a href="members/">members</a>
        </p>
    </div>
{% endblock %}

members/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="container">
        <ul class="nav bg-info">
            <li class="nav-item">
                <a class="nav-link link-light" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="/members">Members</a>
            </li>
        </ul>
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>

members/templates/myfirst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Tennis Club</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>Welcome to my first Django app</p>
</body>
</html>

members/templates/mymenu.html
<div>
    HOME | {{ me }} | ABOUT | FORUM | {{ sponsor }}
</div>

members/templates/template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'myfirst.css' %}"> -->
    <link rel="stylesheet" href="{% static 'myglobal.css' %}">
    <title>Testing</title>
</head>
<body>
    {% include 'mymenu.html' with me='Toby' sponsor='zenlight' %}

    <h1>Hello {{ firstname }}, how are you today?</h1>

    <table border="1">
        <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Joined date</th>
        </tr>
        {% for member in members %}
            <tr>
                <td>{{ member.id }}</td>
                <td>{{ member.firstname }}</td>
                <td>{{ member.lastname }}</td>
                <td>{{ member.joined_date }}</td>
            </tr>
        {% empty %}
            <tr>
                <td>No data</td>
                <td>No data</td>
                <td>No data</td>
            </tr>
        {% endfor %}
    </table>

    <hr>

    <h2>Comment in Django</h2>

    {% comment %}
        <h2>Welcome! This is actually a comment in Django</h2>
    {% endcomment %}

    {% comment "This was another title candidate" %}
        <h1>Hello {{ firstname }}, welcome to Django!</h1>
    {% endcomment %}

    <h3>Welcome, this actually includes a {# real but hidden #} comment</h3>

    <hr>

    <p>In views.py, you can see what the fruits variable looks like</p>
    {% for fruit in fruits %}
        <h3>{{ fruit }}</h3>
    {% endfor %}

    {% with lastname="Refschneider" %}
        <h3>Hello {{ lastname }}, how are you?</h3>
    {% endwith %}

    <hr>

    <h2>if - elif -else</h2>
    {% if greeting == 1 %}
        <h3>Hello</h3>
    {% elif greeting == 2 %}
        <h3>Welcome!</h3>
    {% else %}
        <h3>Goodbye</h3>
    {% endif %}

    <h2>if - AND</h2>
    {% if greeting == 1 and eat_fruits %}
        <h3>Hello and let's eat fruits!</h3>
    {% endif %}

    <hr>

    <h2>if - OR</h2>
    {% if greeting == 1 or eat_fruits %}
        <h3>Hi or let's eat fruits!</h3>
    {% endif %}

    <hr>

    <h2>if - AND/OR</h2>
    {% if greeting == 1 and day == 'Friday' or greeting == 5 %}
        <h3>Hi! Today is Friday</h3>
    {% endif %}

    {% comment 'Parentheses such following, are not allowed in if statements in Django' %}
        {% if (greeting == 1 and day = 'Friday') or greeting == 5 %}
            <h3>Hi today is Friday or greeting is 5</h3>
        {% endif %}
    {% endcomment %}

    <hr>

    <h2>in</h2>

    {% if 'Banana' in fruits %}
        <h3>Banana is included in fruits</h3>
    {% else %}
        <h3>Banana is excluded in fruits</h3>
    {% endif %}

    <hr>

    <h2>not in</h2>

    {% if 'Manggo' not in fruits %}
        <h3>Manggo is not in fruits variable</h3>
    {% else %}
        <h3>Manggo is in fruits variable</h3>
    {% endif %}

    <hr>

    <h2>is</h2>

    {% if fruits == fav_food %}
        <h3>The value of fruits and fav_food variables are same</h3>
    {% else %}
        <h3>fruits and fav_food variables are not the same</h3>
    {% endif %}

    <br>

    {% with var1=fruits var2=fruits %}
        {% if var1 is var2 %}
            <h3>var1 is equal var2</h3>
        {% else %}
            <h3>var1 IS NOT equal var2</h3>
        {% endif %}
    {% endwith %}

    {% comment 'The following would not assign values to var1 and var2, therefore causes an error' %}
        {% with var1 = fruits var2 = fruits %}
    {% endcomment %}

    <hr>

    <h2>is not</h2>

    {% if fruits is not fav_food %}
        <h3>Fruits variable is not fav_food variable</h3>
    {% else %}
        <h3>Fruits variable is fav_food variable</h3>
    {% endif %}

    <hr>

    <h2>for loop -reversed</h2>

    {% for member in members reversed %}
        <h3>Member ID: {{ member.id }}</h3>
        <p>
            {{ member.firstname }} {{ member.lastname }}
        </p>
    {% endfor %}

    <hr>

    <h2>for loop - empty (keyword)</h2>

    <!-- 'emptytestobject' is a non-existent object, by all means -->
    <ul>
        {% for x in emptytestobject %}
            <li>{{ x.firstname }}</li>
        {% empty %}
            <li>No members</li>
        {% endfor %}
    </ul>

    <hr>

    <h2>for Loop Variables - counter</h2>

    <ul>
        {% for fruit in fruits %}
            <li>
                forloop.counter: {{ forloop.counter }}
            </li>
        {% endfor %}
    </ul>

    <hr>

    <h2>for Loop Variables - counter0</h2>

    <ul>
        {% for fruit in fruits %}
            <li>forloop.counter0: {{ forloop.counter0 }}</li>
        {% endfor %}
    </ul>

    <hr>

    <h2>for Loop Variables - first</h2>

    <ul>
        {% for fruit in fruits %}
            <li 
                {% if forloop.first %}
                    style="background-color: lightblue;"
                {% endif %}
            >
                forloop.first: {{ fruit }}
            </li>
        {% endfor %}
    </ul>

    <hr>

    <h2>for Loop Variables - last</h2>

    <ul>
        {% for fruit in fruits %}
            <li
                {% if forloop.last %}
                    style="background-color: aquamarine;"
                {% endif %}
            >
                forloop.last: {{ fruit }}
            </li>
        {% endfor %}
    </ul>

    <hr>

    <h2>for Loop Variables - revcounter</h2>

    <ul>
        {% for fruit in fruits %}
            <li>
                forloop.revcounter: {{ forloop.revcounter }}
            </li>
        {% endfor %}
    </ul>

    <hr>

    {% include 'footer.html' %}
</body>
</html>